#!/usr/bin/env bash
# Mosh with automatic reverse tunnel setup
# Usage: mosh-with-tunnel <remote-host> [remote-user] [mosh-args...]
#        mt <remote-host> [remote-user] [mosh-args...]  (alias)
#
# Establishes a reverse SSH tunnel in background, then connects with Mosh.
# On the remote, you can use 'tunnel-open' and 'beep' to interact with your local machine.

HOST="${1:?Usage: mosh-with-tunnel <remote-host> [remote-user] [mosh-args...]}"
shift

REMOTE_USER="${TUNNEL_REMOTE_USER:-$USER}"
if [ $# -gt 0 ] && [[ "$1" != -* ]]; then
  REMOTE_USER="$1"
  shift
fi

tunnel-setup "$HOST" "$REMOTE_USER"

if command -v mosh &>/dev/null; then
  mosh "$REMOTE_USER@$HOST" "$@"
else
  if [ "${1:-}" = "--" ]; then
    shift
  fi
  if command -v caffeinate &>/dev/null; then
    caffeinate -i ssh "$REMOTE_USER@$HOST" "$@"
  else
    ssh "$REMOTE_USER@$HOST" "$@"
  fi
fi
