#!/usr/bin/env bash

if [[ -n "$TMUX" && -n "$TMUX_PANE" ]]; then
  window_id=$(tmux display-message -p -t "$TMUX_PANE" '#{window_id}')
  [[ -n "$window_id" ]] && tmux rename-window -t "$window_id" "pi"
fi

export PI_EXTENSION_CONFIG_DIR="${PI_EXTENSION_CONFIG_DIR:-$HOME/.pi/agent/extension-config}"
if [[ -n "$TMUX" ]]; then
  export PI_TMUX_IMAGES="${PI_TMUX_IMAGES:-1}"
fi

pi_bin=$(mise which pi)
if [[ -n "$TMUX" && -z "${PI_SKIP_TMUX_IMAGE_PATCH:-}" ]]; then
  pi_real=$(readlink -f "$pi_bin")
  pi_root=$(dirname "$(dirname "$pi_real")")
  patch_marker="$pi_root/.rich-pi-tmux-images-v3.json"
  if [[ ! -f "$patch_marker" && -x "$HOME/Scripts/pi-patch-tmux-images" ]]; then
    "$HOME/Scripts/pi-patch-tmux-images" "$pi_bin" || true
  fi
fi

"$pi_bin" "$@"
