#!/usr/bin/env bash

last_session=$(tmux list-sessions -F '#{session_last_attached} #{session_name}' | sort -rn | head -1 | cut -d' ' -f2-)

if [[ -z "$last_session" ]]; then
  if tmux has-session -t code 2>/dev/null; then
    last_session="code"
  else
    last_session=$(tmux list-sessions -F '#{session_name}' | head -1)
  fi
fi

last_window=$(tmux list-windows -t "$last_session" -F '#{window_activity} #{window_index}' | sort -rn | head -1 | cut -d' ' -f2)

tmux attach -t "$last_session:$last_window"
