#!/usr/bin/env bash

source "$(dirname "$0")/tmux-setup-windows"
# Strip the first two chars which are icons, but only if arg doesn't contain a space
if [[ "$1" == *" "* ]]; then
  arg="${1:2}"
else
  arg="$1"
fi

expanded_path="${arg/#\~/$HOME}"

if [ -d "$expanded_path" ]; then
  create_session_for_path "$expanded_path" >/dev/null
  exit 0
fi

sesh connect "$arg" >/dev/null
