#!/usr/bin/env bash
# open command so that linux open works like macOS `open`
# on macOS /usr/bin/open takes priority on the $PATH, so this is never used

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: open <file-or-url>" >&2
  exit 1
fi

if [[ "$1" =~ ^https?:// ]]; then
  exec tunnel-browser-open "$1"
fi

exec xdg-open "$1"
