#!/usr/bin/env bash
# Source: https://github.com/suan/local-open
#
# If running locally opens using xdg-open or open
# If an SSH session is active it ssh's back to the client assuming that a reverse ssh tunnel is active
# Start a tunnel with local-open-tunnel
# Remember the the local machine also needs SSH server enabled
if [[ -f ~/.localopenrc ]]; then
  . ~/.localopenrc
fi
user=${LOCAL_OPEN_USER-$USER}
alt_localhost=${ALT_LOCALHOST-`hostname`}
url=$1
open_cmd=${LOCAL_OPEN_CMD-"open"}
host=${LOCAL_OPEN_HOST-"localhost"}
port=${LOCAL_OPEN_PORT-1999}

if [[ -z $SSH_CLIENT ]] && [[ -z $SSH_TTY ]]; then
  if hash xdg-open 2>/dev/null; then
    open_cmd=`which xdg-open`
  else
    open_cmd=`which open`
  fi
  # xdg-open was printing weird output, supress it
  $open_cmd "$url" &>/dev/null
else
  if [[ "$url" == *localhost* ]]; then
    url=${url/localhost/$alt_localhost}
  elif [[ "$url" == *"127.0.0.1"* ]]; then
    url=${url/127\.0\.0\.1/$alt_localhost}
  elif [[ "$url" == *"0.0.0.0"* ]]; then
    url=${url/0\.0\.0\.0/$alt_localhost}
  fi
  ssh -l $user -p $port $host "$open_cmd \"$url\""
fi
