#!/usr/bin/env bash

set -euo pipefail
# When sshing in and connecting via tmux, tmux doesn't update the 'environment' vars# until you switch sessions. We trick it by switching to the same session 

if [[ -z "${TMUX:-}" ]]; then
  echo "Not in a tmux session" >&2
  exit 1
fi

session=$(tmux display-message -p '#S')
tmux switch-client -t "$session"
tmux display-message "SSH environment refreshed"
