#!/usr/bin/env bash

create_worktree_session() {
  local expanded_path="$1"
  session_name="$(basename "$(dirname "$expanded_path")")/$(basename "$expanded_path")"
  tmux new-session -d -s "$session_name" -c "$expanded_path"
  tmux switch-client -t "$session_name"
  echo "$session_name"
}

setup_tmux_windows() {
  local session_name="$1"
  if [ -z "$session_name" ] && [ -n "$TMUX" ]; then
    session_name=$(tmux display-message -p "#{session_name}")
  fi
  
  if [ -n "$session_name" ]; then
    ORIGINAL_WINDOW=$(tmux display-message -t "$session_name" -p "#{window_id}")
    ORIGINAL_PANE=$(tmux display-message -t "$session_name" -p "#{pane_id}")
    ORIGINAL_PATH=$(tmux display-message -t "$session_name" -p "#{pane_current_path}")
    
    tmux rename-window -t "$ORIGINAL_WINDOW" "nvim"

    SOCKET_FILE="/tmp/nvim-socket-$(uuidgen)"
    tmux send-keys -t "$ORIGINAL_PANE" "v . --listen $SOCKET_FILE" Enter

    tmux new-window -t "$session_name" -a -c "$ORIGINAL_PATH" -n "short"
    tmux new-window -t "$session_name" -a -c "$ORIGINAL_PATH" -n "long"

    AI_WINDOW_1=$(tmux new-window -t "$session_name" -a -c "$ORIGINAL_PATH" -n "ai1" -P -F "#{window_id}")
    tmux send-keys -t "$AI_WINDOW_1" "cl" Enter

    AI_WINDOW_2=$(tmux new-window -t "$session_name" -a -c "$ORIGINAL_PATH" -n "ai2" -P -F "#{window_id}")
    tmux send-keys -t "$AI_WINDOW_2" "cl" Enter

    tmux select-window -t "$AI_WINDOW_1"
    
    echo "$SOCKET_FILE"
  fi
}
