{
  imports = [
    ../shared/headless
    ../shared/graphical
    ../shared/graphical/qmk-keyboard-setup.nix
    ./dock.nix
    ./eternal-terminal-server.nix
    ./home-manager.nix
    ./keyboard.nix
    ./networking.nix
    ./nix.nix
    ./packages.nix
    ./secrets.nix
    ./security.nix
    ./ssh.nix
    ./stylix.nix
    ./system-defaults.nix
    ./users.nix
  ];
}
