name: Nix Configuration Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run checks
        run: just check